version: '3.2'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - './uptime-kuma/data:/app/data'
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Bucharest'
      WEBPASSWORD: 'vladminmax.'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: always

  registry:
    container_name: docker-registry
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry/data:/var/lib/registry
      - ./docker-registry-config.yaml:/etc/docker/registry/config.yml
    restart: unless-stopped
    
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: docker-registry-ui
    ports:
      - 81:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://charlie.lan:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry