---
- name: Update all installed packages using APT module
  apt:
    update_cache: true
    upgrade: 'yes'
    cache_valid_time: 3600

- name: Remove packages not needed anymore
  apt:
    autoremove: yes