prometheus:
  prometheusSpec:
    retention: 365d
    retentionSize: 15GB
    additionalScrapeConfigs:
    - job_name: rpi-cluster
      scrape_interval: 10s
      static_configs:
        - targets: [ 'foxtrot-svc-ext:9100' ]
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 15Gi
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false

#disable alertmanager
defaultRules:
  rules:
    alertmanager: false

alertmanager:
  enabled: false

#grafana
grafana:
  storageClassName: "longhorn"
  accessModes:
  - ReadWriteOnce
  size: 7Gi
  finalizers:
  - kubernetes.io/pvc-protection
  adminPassword: vladminmax.2251

