prometheus:
  prometheusSpec:
    retention: 365d
    retentionSize: 10GB
    additionalScrapeConfigs:
    - job_name: rpi-cluster
      scrape_interval: 15s
      static_configs:
        - targets: [ 'foxtrot-svc-ext:9100' ]
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "local-path"
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false

#disable alertmanager
defaultRules:
  rules:
    alertmanager: false

alertmanager:
  enabled: false

#grafana
grafana:
  persistence:
    enabled: true
    size: 7Gi

