global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'nodes'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.7.173:9100']
        labels:
          server: 'sierra'
      - targets: ['192.168.7.176:9100']
        labels:
          server: 'lima'

  - job_name: 'docker-daemon'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.7.173:9323']
        labels:
          server: 'sierra'
      - targets: ['192.168.7.176:9323']
        labels:
          server: 'lima'